import {
  FlaticonIcon,
  PagekitIcon,
  InternetHardIcon,
  MollieIcon,
  Ui8Icon,
  MapboxIcon,
  ExpoIcon,
  FrappeIcon,
  SeoIcon,
  DevhintsIcon,
  WorldVectorLogoIcon,
  ObservableIcon,
  FontBaseIcon,
  RealfavicongeneratorIcon,
  ProductHuntIcon,
  DraggableIcon,
  FigmaIcon,
  FeatherIconsIcon,
  IftttIcon,
  JestIcon,
  CoolhueIcon,
  Icons8Icon,
  TheInternIcon,
  DimensionsIcon,
  SocialsizesIcon,
  SteciljsIcon,
} from "../components/atoms/Icons";

const links = [
  {
    title: "Steciljs",
    description: "Web component compiler",
    link: "https://stenciljs.com/",
    icon: SteciljsIcon,
  },
  {
    title: "Socialsizes",
    description: "All sizes of all socials",
    link: "https://socialsizes.io/",
    icon: SocialsizesIcon,
  },
  {
    title: "Dimensions",
    description: "Comprehensive ref. database",
    link: "https://www.dimensions.com/",
    icon: DimensionsIcon,
  },
  {
    title: "The Intern",
    description: "You deserve some help",
    link: "https://theintern.io/",
    icon: TheInternIcon,
  },
  {
    title: "Icons8",
    description: "Quality visuals",
    link: "https://icons8.com/",
    icon: Icons8Icon,
  },
  {
    title: "CoolHue 2.0",
    description: "Gradient Hues and Swatches",
    link: "https://webkul.github.io/coolhue/",
    icon: CoolhueIcon,
  },
  {
    title: "Jest",
    description: "Delightful JavaScript Testing",
    link: "https://jestjs.io/",
    icon: JestIcon,
  },
  {
    title: "IFTTT",
    description: "If This Then That",
    link: "https://ifttt.com/explore",
    icon: IftttIcon,
  },
  {
    title: "Feather icons",
    description: "Beautiful open source icons",
    link: "https://feather.netlify.app/",
    icon: FeatherIconsIcon,
  },
  {
    title: "Figma",
    description: "Prototype faster and better",
    link: "https://www.figma.com/",
    icon: FigmaIcon,
  },
  {
    title: "Draggable",
    description: "Modern drag and drop",
    link: "https://shopify.github.io/draggable/examples/simple-list.html",
    icon: DraggableIcon,
  },
  {
    title: "Product Hunt",
    description: "Find your next favorite thing",
    link: "https://www.producthunt.com/",
    icon: ProductHuntIcon,
  },
  {
    title: "Realfavicongenerator",
    description: "All the favicons generated!",
    link: "https://realfavicongenerator.net/",
    icon: RealfavicongeneratorIcon,
  },
  {
    title: "Fontbase",
    description: "Font management. Perfected.",
    link: "https://fontba.se/",
    icon: FontBaseIcon,
  },
  {
    title: "Observable",
    description: "Free interactive notebooks",
    link: "https://observablehq.com/",
    icon: ObservableIcon,
  },
  {
    title: "World Vector Logo",
    description: "All brands, all logos",
    link: "https://worldvectorlogo.com/",
    icon: WorldVectorLogoIcon,
  },
  {
    title: "Devhints",
    description: "Massive cheatsheets",
    link: "https://devhints.io/",
    icon: DevhintsIcon,
  },
  {
    title: "Frappe",
    description: "Dem fancy charts",
    link: "https://frappe.io/charts",
    icon: FrappeIcon,
  },
  {
    title: "Expo",
    description: "Native apps with JS",
    link: "https://docs.expo.io/",
    icon: ExpoIcon,
  },
  {
    title: "SEO",
    description: "All the tips and tricks",
    link: "https://backlinko.com/seo-this-year",
    icon: SeoIcon,
  },
  {
    title: "Mapbox",
    description: "Location, location, location",
    link: "https://www.mapbox.com/",
    icon: MapboxIcon,
  },
  {
    title: "UI8",
    description: "Design Inspiriation +1",
    link: "https://www.ui8.net/",
    icon: Ui8Icon,
  },
  {
    title: "Mollie",
    description: "Mo money mo problems",
    link: "https://www.mollie.com",
    icon: MollieIcon,
  },
  {
    title: "Internetingishard",
    description: "A HTML & CSS tutorial",
    link: "https://www.internetingishard.com/",
    icon: InternetHardIcon,
  },
  {
    title: "Pagekit",
    description: "Awesome free CMS",
    link: "https://pagekit.com/",
    icon: PagekitIcon,
  },
  {
    title: "Flaticon",
    description: "Free flaticon(s) database",
    link: "https://www.flaticon.com/",
    icon: FlaticonIcon,
  },
];

export default links;
