# ~/static/admin/config.yml

backend:
  name: git-gateway
  branch: rework-svelte

local_backend: true

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "writing"
    label: "Writing"
    folder: "static/writing"
    create: true
    fields:
      - { label: "Folder", name: "folder", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Header", name: "header", widget: "string" }
      - { label: "Collection", name: "collection", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Filters", name: "filters", widget: "string" }
      - { label: "Icons", name: "icons", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "coding"
    label: "Coding"
    folder: "static/coding"
    create: true
    fields:
      - { label: "Folder", name: "folder", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Online", name: "online", widget: "boolean" }

  - name: "designing"
    label: "Designing"
    folder: "static/designing"
    create: true
    fields:
      - { label: "Folder", name: "folder", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Background", name: "background", widget: "string" }

  - name: "gaming"
    label: "Gaming"
    folder: "static/gaming"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Collection", name: "collection", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
