# ~/static/admin/config.yml

backend:
  name: git-gateway
  branch: rework-svelte

local_backend: true

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "writing"
    label: "Writing"
    folder: "static/writing"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Collection", name: "collection", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "coding"
    label: "Coding"
    folder: "static/coding"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Collection", name: "collection", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
